version: "3.9"

services:
  streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    command: streamlit run app.py --server.port=8501 --server.address=0.0.0.0
